# Generated by Django 2.0.2 on 2018-02-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('startlat', models.FloatField()),
                ('startlong', models.FloatField()),
                ('endlat', models.FloatField()),
                ('endlong', models.FloatField()),
                ('torrsprederaktiv', models.BooleanField()),
                ('plogaktiv', models.BooleanField()),
                ('vatsprederaktiv', models.BooleanField()),
                ('materialtype_kode', models.BooleanField()),
                ('from_vegref', models.CharField(max_length=22)),
                ('to_vegref', models.CharField(max_length=22)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
