# Generated by Django 2.0.2 on 2018-03-16 15:16

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('api', '0002_auto_20180309_1146'), ('api', '0003_auto_20180309_1154'), ('api', '0004_auto_20180309_1341'), ('api', '0005_auto_20180309_1547'), ('api', '0006_auto_20180312_1338')]

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('startlat', models.FloatField()),
                ('startlong', models.FloatField()),
                ('endlat', models.FloatField()),
                ('endlong', models.FloatField()),
                ('dry_spreader_active', models.NullBooleanField()),
                ('plow_active', models.NullBooleanField()),
                ('wet_spreader_active', models.NullBooleanField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('material_type_code', models.IntegerField(null=True)),
                ('brush_active', models.NullBooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
