# Generated by Django 2.0.2 on 2018-03-09 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('startlat', models.FloatField()),
                ('startlong', models.FloatField()),
                ('endlat', models.FloatField()),
                ('endlong', models.FloatField()),
                ('torrsprederaktiv', models.BooleanField()),
                ('plogaktiv', models.BooleanField()),
                ('vatsprederaktiv', models.BooleanField()),
                ('materialtype_kode', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
