# Generated by Django 2.0.2 on 2018-04-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180309_1146_squashed_0006_auto_20180312_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondata',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
