# Generated by Django 2.0.2 on 2018-04-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180409_1251_squashed_0003_auto_20180409_1254'),
        ('api', '0002_auto_20180309_1146_squashed_0006_auto_20180312_1338'),
    ]

    operations = [
    ]
