# Generated by Django 2.0.2 on 2018-03-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180309_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondata',
            name='materialtype_kode',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
