# Generated by Django 2.0.2 on 2018-04-13 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20180411_0944'),
        ('api', '0004_dummymodel_squashed_0009_auto_20180411_1244'),
    ]

    operations = [
    ]
