# Generated by Django 2.0.2 on 2018-03-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180309_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productiondata',
            old_name='torrsprederaktiv',
            new_name='dry_spreader_active',
        ),
        migrations.RenameField(
            model_name='productiondata',
            old_name='plogaktiv',
            new_name='plow_active',
        ),
        migrations.RenameField(
            model_name='productiondata',
            old_name='vatsprederaktiv',
            new_name='wet_spreader_active',
        ),
        migrations.RemoveField(
            model_name='productiondata',
            name='materialtype_kode',
        ),
        migrations.AddField(
            model_name='productiondata',
            name='material_type_code',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
