# Generated by Django 2.0.2 on 2018-04-09 12:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dummymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummymodel',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326),
        ),
    ]
