# Generated by Django 2.0.2 on 2018-04-13 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20180413_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondata',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RoadSegment'),
        ),
        migrations.AlterField(
            model_name='roadsegment',
            name='stretchdistance',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='DummyModel',
        ),
    ]
