# Generated by Django 2.0.2 on 2018-04-09 13:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180409_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dummymodel',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326),
        ),
    ]
