# Generated by Django 2.0.2 on 2018-03-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180309_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondata',
            name='brush_active',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='material_type_code',
            field=models.IntegerField(null=True),
        ),
    ]
