# Generated by Django 2.0.2 on 2018-04-13 12:09

import django.contrib.gis.db.models.fields
from django.db import migrations
from django.contrib.gis.geos import GEOSGeometry


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180413_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadsegment',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='roadsegment',
            name='srid',
        ),
        migrations.AddField(
            model_name='roadsegment',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.LineStringField(default=GEOSGeometry(
                'LINESTRING(10.5361787687115 63.4125731083948,10.5361924532311 63.4126037467593,10.5361945043349 63.4126150498519,10.5361988291749 63.4126400906091,10.5362027264781 63.4126691640008,10.5362050948012 63.412713204752,10.5362072868341 63.4127558014056,10.5362030682502 63.4127841713201,10.5361941556484 63.4128117649947,10.5361807814375 63.4128358024478,10.536170277635 63.4128491403433,10.5361609397018 63.4128575695899)'), srid=4326),
            preserve_default=False,
        ),
    ]
