# Generated by Django 2.0.2 on 2018-04-11 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_postgis'),
    ]

    operations = [
        migrations.AddField(
            model_name='productiondata',
            name='segment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.RoadSegment'),
            preserve_default=False,
        ),
    ]
