# Generated by Django 2.0.2 on 2018-04-11 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_productiondata_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondata',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DummyModel'),
        ),
    ]
