# Generated by Django 2.0.2 on 2018-04-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20180418_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('time', models.DateTimeField()),
                ('municipality', models.IntegerField()),
                ('value', models.IntegerField()),
                ('unit', models.CharField(max_length=2)),
                ('degrees', models.IntegerField()),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RoadSegment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
