from django.db import models


class RoadSegment(models.Model):
    id = models.AutoField(primary_key=True)
    time = models.DateTimeField()
    coordinates = models.CharField(max_length=500)
    fra_meter = models.IntegerField()
    fylke = models.IntegerField()
    srid = models.IntegerField()
    hp = models.IntegerField()
    href = models.CharField(max_length=100)
    kategori = models.CharField(max_length=3)
    kommune = models.IntegerField()
    konnekteringslenke = models.BooleanField()
    kortform = models.CharField(max_length=150)
    medium = models.CharField(max_length=1)
    startdato = models.CharField(max_length=12)
    nummer = models.IntegerField()
    region = models.IntegerField()
    sluttnode = models.CharField(max_length=20)
    sluttposisjon = models.FloatField()
    startnode = models.IntegerField()
    startposisjon = models.FloatField()
    status = models.CharField(max_length=3)
    strekningslengde = models.IntegerField()
    temakode = models.IntegerField()
    til_meter = models.IntegerField()
    typeveg = models.CharField(max_length=50)
    vegavdeling = models.IntegerField()
    veglenkeid = models.IntegerField()
    vrefkortform = models.CharField(max_length=150)
