from django.db import models


class RoadSegment(models.Model):
    id = models.AutoField(primary_key=True)
    coordinates = models.TextField()
    from_meter = models.IntegerField()
    county = models.IntegerField()
    srid = models.IntegerField()
    hp = models.IntegerField()
    href = models.CharField(max_length=150)
    category = models.CharField(max_length=4)
    municipality = models.IntegerField()
    connlink = models.BooleanField()
    shortform = models.CharField(max_length=255)
    medium = models.CharField(max_length=4)
    startdate = models.CharField(max_length=50)
    number = models.IntegerField()
    region = models.IntegerField()
    endnode = models.CharField(max_length=255)
    endposition = models.FloatField()
    startnode = models.CharField(max_length=100)
    startposition = models.FloatField()
    status = models.CharField(max_length=4)
    stretchdistance = models.IntegerField()
    themecode = models.IntegerField()
    to_meter = models.IntegerField()
    typeofroad = models.CharField(max_length=100)
    roadsection = models.IntegerField()
    roadsectionid = models.IntegerField()
    vrefshortform = models.CharField(max_length=255)
