from django.db import models


class RoadSegment(models.Model):
    id = models.AutoField(primary_key=True)
    coordinates = models.TextField()
    fra_meter = models.IntegerField()
    fylke = models.IntegerField()
    srid = models.IntegerField()
    hp = models.IntegerField()
    href = models.CharField(max_length=150)
    kategori = models.CharField(max_length=4)
    kommune = models.IntegerField()
    konnekteringslenke = models.BooleanField()
    kortform = models.CharField(max_length=255)
    medium = models.CharField(max_length=4)
    startdato = models.CharField(max_length=50)
    nummer = models.IntegerField()
    region = models.IntegerField()
    sluttnode = models.CharField(max_length=255)
    sluttposisjon = models.FloatField()
    startnode = models.CharField(max_length=100)
    startposisjon = models.FloatField()
    status = models.CharField(max_length=4)
    strekningslengde = models.IntegerField()
    temakode = models.IntegerField()
    til_meter = models.IntegerField()
    typeveg = models.CharField(max_length=100)
    vegavdeling = models.IntegerField()
    veglenkeid = models.IntegerField()
    vrefkortform = models.CharField(max_length=255)
