# Generated by Django 2.0.2 on 2018-05-09 12:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('time', models.DateTimeField()),
                ('startlat', models.FloatField()),
                ('startlong', models.FloatField()),
                ('start_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('endlat', models.FloatField()),
                ('endlong', models.FloatField()),
                ('end_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('dry_spreader_active', models.NullBooleanField()),
                ('plow_active', models.NullBooleanField()),
                ('wet_spreader_active', models.NullBooleanField()),
                ('brush_active', models.NullBooleanField()),
                ('material_type_code', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('county', models.IntegerField(help_text='County identifier.  Example: 50')),
                ('href', models.CharField(help_text='Link to NVDB for this unique segment', max_length=150)),
                ('category', models.CharField(help_text='Road segment category. Example: K', max_length=4)),
                ('municipality', models.IntegerField(help_text='Municipality number for that county.Example: 01 for Trondheim')),
                ('startdate', models.DateField(help_text='Start date for the road segment. Example: 2018-04-20')),
                ('region', models.IntegerField(help_text='Region number. Example: 4')),
                ('status', models.CharField(help_text='Road status. Example: G', max_length=4)),
                ('stretchdistance', models.IntegerField(help_text='Length of the road segment. Example 31')),
                ('typeofroad', models.CharField(help_text='A description of the road type. Example: gangOgSykkelvei', max_length=100)),
                ('roadsectionid', models.IntegerField(help_text='Unique identifier for the road segment. Example: 171712')),
                ('vrefshortform', models.CharField(help_text='A combination of multiple fields. Example: 5001 Kg97587 hp1 m349-380', max_length=255)),
                ('the_geom', django.contrib.gis.db.models.fields.LineStringField(help_text='Linestring according to ISO 19162:2015. Example: SRID=4326;LINESTRING (10.37634290477487 63.3478716972899, 10.37656821856063 63.34786722088941)', srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productiondata',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RoadSegment'),
        ),
    ]
