# Generated by Django 2.0.2 on 2018-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_auto_20180404_1459'), ('api', '0003_remove_roadsegment_time'), ('api', '0004_auto_20180406_1245'), ('api', '0005_auto_20180406_1300'), ('api', '0006_auto_20180406_1308'), ('api', '0007_auto_20180406_1311'), ('api', '0008_auto_20180406_1435'), ('api', '0009_auto_20180409_0903')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sluttposisjon', models.FloatField()),
                ('startposisjon', models.FloatField()),
                ('konnekteringslenke', models.BooleanField()),
                ('coordinates', models.TextField()),
                ('fra_meter', models.IntegerField(default=1)),
                ('fylke', models.IntegerField(default=1)),
                ('hp', models.IntegerField(default=1)),
                ('href', models.CharField(max_length=150)),
                ('kategori', models.CharField(max_length=4)),
                ('kommune', models.IntegerField(default=1)),
                ('kortform', models.CharField(default=1, max_length=255)),
                ('medium', models.CharField(max_length=4)),
                ('nummer', models.IntegerField(default=1)),
                ('region', models.IntegerField(default=1)),
                ('sluttnode', models.CharField(default=1, max_length=255)),
                ('srid', models.IntegerField(default=1)),
                ('startdato', models.CharField(max_length=50)),
                ('startnode', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=4)),
                ('strekningslengde', models.IntegerField(default=1)),
                ('temakode', models.IntegerField(default=1)),
                ('til_meter', models.IntegerField(default=1)),
                ('typeveg', models.CharField(max_length=100)),
                ('vegavdeling', models.IntegerField(default=1)),
                ('veglenkeid', models.IntegerField(default=1)),
                ('vrefkortform', models.CharField(default=1, max_length=255)),
            ],
        ),
    ]
