# Generated by Django 2.0.2 on 2018-04-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180418_1013'),
        ('api', '0007_auto_20180413_1209'),
    ]

    operations = [
    ]
