# Generated by Django 2.0.2 on 2018-05-02 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180502_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='municipality',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='county_and_municipality_id',
            field=models.IntegerField(default=1, help_text='County and municipality number put together.Example: 5001 for Trondheim'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='degrees',
            field=models.IntegerField(help_text='The degree measured in celsius.'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='segment',
            field=models.ForeignKey(help_text='Segment ID to mapped segment. Will be autocompleted by the code. Enter dummy value.', on_delete=django.db.models.deletion.CASCADE, to='api.RoadSegment'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='time',
            field=models.DateTimeField(help_text='When the weather data was generated. Example: 2018-12-09T08:45:15Z'),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='unit',
            field=models.CharField(help_text='The unit describing the value. Max two in length. Example: mm for millimeter', max_length=2),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='value',
            field=models.IntegerField(help_text='The amount of precipitation without the unit. Example: 2'),
        ),
    ]
