# Generated by Django 2.0.2 on 2018-04-30 15:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180430_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondata',
            name='closest_point',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
