# Generated by Django 2.0.2 on 2018-05-02 10:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.contrib.gis.geos.point


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180430_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productiondata',
            old_name='closest_point',
            new_name='start_point',
        ),
        migrations.AddField(
            model_name='productiondata',
            name='end_point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, default=django.contrib.gis.geos.point.Point(10.356343049613752, 63.397435490163907), srid=4326),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='endlat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='endlong',
            field=models.FloatField(null=True),
        ),
    ]
